player:
    resource: MPD\RestBundle\Controller\PlayerController
    type: rest
    
settings:
    resource: MPD\RestBundle\Controller\SettingsController
    type: rest
    
file-system:
    resource: MPD\RestBundle\Controller\FileSystemController
    type: rest
    
playlist:
    resource: MPD\RestBundle\Controller\PlaylistController
    type: rest
    
#mpd_rest_track_play:
#    path:     /play/{id}
#    defaults: { _controller: MPDRestBundle:Track:play, id: 0 }
#    
