tracks:
    resource: MPD\RestBundle\Controller\TrackController
    type: rest
    
#mpd_rest_track_play:
#    path:     /play/{id}
#    defaults: { _controller: MPDRestBundle:Track:play, id: 0 }
#    
